spring:
  flyway:
    enabled: false
    locations: classpath:db/migration

tenants:
  datasources:
    vw:
      jdbcUrl: jdbc:postgresql://localhost:5432/multi_tenancy
      driverClassName: org.postgresql.Driver
      username: postgres
      password: roor
    bmw:
      jdbcUrl: jdbc:postgresql://localhost:5432/multi_tenancy1
      driverClassName: org.postgresql.Driver
      username: postgres
      password: roor
    default:
      jdbcUrl: jdbc:postgresql://localhost:5432/public
      driverClassName: org.postgresql.Driver
      username: postgres
      password: roor


